
CREATE DATABASE BIBLIOTECAUH
USE BIBLIOTECAUHCREATE TABLE LIBROS (   ID INT identity PRIMARY KEY,   Titulo VARCHAR(100) NOT NULL,   Autor VARCHAR(100) NOT NULL,   Anno INT,   Precio DECIMAL(10,2),   Disponible VARCHAR(1) ,   CHECK (Disponible IN ('S','N')));

INSERT INTO LIBROS (Titulo, Autor, Anno, Precio,Disponible)VALUES('UN MUNDO FELIZ', 'ALDO HUXLEY', 2000, 6000, 'S'),('ORGULLO ', 'JANE AUSTEN', 2001, 7000, 'N'),('CRIMEN Y CASTIGO', 'FIODOR DOSTOYEVSKI', 1999, 10000, 'S'),('MADAME BOVARY', 'GUSTAVE', 2005, 4000, 'S'),('EN BUSCA DEL TIEMPO', 'MARCEL PROUST', 2010, 35000, 'N');SELECT * FROM LIBROS; 